baseURL = 'https://nerdxio.github.io/'
languageCode = 'en-us'
title = 'Hassan Refaat'
theme = 'hugo-theme-stack'

# Menu configuration
[menu]
    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com"
        [menu.social.params]
            icon = "brand-github"
            
    [[menu.social]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/YourTwitterHandle"
        [menu.social.params]
            icon = "brand-twitter"
            
    [[menu.social]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/YourLinkedInProfile"
        [menu.social.params]
            icon = "linkedin"
            
    [[menu.social]]
        identifier = "cv"
        name = "Resume/CV"
        url = "/resume.pdf"  # Update this path to where your CV is stored
        [menu.social.params]
            icon = "cv"

# Site parameters
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.footer]
        since = 2020
        customText = ""

    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

    [params.article]
        math = false
        toc = true
        readingTime = true

    [params.comments]
        enabled = false
        provider = "disqus"

    [params.sidebar]
        emoji = "🚀"
        subtitle = "Crafting elegant solutions through code"
        [params.sidebar.avatar]
            enabled = true
            local = false
            src = "/img/gogo.png"

    [params.widgets]
        homepage = [
            {type = "search"},
            {type = "archives", params = { limit = 5 }},
            {type = "tag-cloud", params = { limit = 10 }}
        ]
        page = [
            {type = "toc"}
        ]

    customCSS = ["css/custom.css"]

# Related content configuration
[related]
    includeNewer = true
    threshold = 60
    toLower = false
    
    [[related.indices]]
        name = "tags"
        weight = 100
    
    [[related.indices]]
        name = "categories"
        weight = 80
    
    [[related.indices]]
        name = "date"
        weight = 10

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4