baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hassan Refaat'
theme = 'hugo-theme-stack'

# Menu configuration
[menu]
    [[menu.social]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com"
        [menu.social.params]
            icon = "brand-github"

# Site parameters
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.footer]
        since = 2020
        customText = ""

    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"

    [params.article]
        math = false
        toc = true
        readingTime = true

    [params.comments]
        enabled = false
        provider = "disqus"

    [params.sidebar]
        emoji = "🚀"
        subtitle = "Crafting elegant solutions through code"
        [params.sidebar.avatar]
            enabled = true
            local = false
            src = "/img/gogo.png"

    [params.widgets]
        homepage = [
            {type = "search"},
            {type = "archives", params = { limit = 5 }},
            {type = "tag-cloud", params = { limit = 10 }}
        ]
        page = [
            {type = "toc"}
        ]

    customCSS = ["css/custom.css"]

[markup]
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4